"""Sample diffusion paths using exact range reconstruction and Poisson rejection.

Algorithm01_Vanilla proposes a Brownian bridge, reconstructs its extrema,
and samples its values at Poisson test times. Accepted draws retain these
values and extrema so that additional path values can be sampled later.
Set z to sample a diffusion bridge with a fixed final endpoint; otherwise
the endpoint is sampled using the model's proposal distribution.

Algorithm01_Vanilla_refine samples additional values conditional on an
accepted draw. Algorithm01_Vanilla_summary reports its sampling statistics.

Reference: Paper_H200.pdf, Algorithm 2, Sections 3.3-3.4. The restricted
meander extrema are generated by RBMMax_Vanilla.
"""

import math
import random
from time import perf_counter

from .BRIDGEMAX import BRIDGEMAX
from .RBMMax_Vanilla import RBMMax_Vanilla
from .ICB_samplers import ICB


def _algorithm01_vanilla_check_scalar(value, name, positive=False):
    """Check that value is one finite number, and optionally positive."""
    is_number = isinstance(value, (int, float)) and not isinstance(value, bool)
    if not is_number or not math.isfinite(value):
        raise ValueError(f"{name} must be a finite scalar")
    if positive and value <= 0:
        raise ValueError(f"{name} must be positive")


def _algorithm01_vanilla_check_integer(value, name, positive=False):
    """Check that value is finite and integer-valued."""
    _algorithm01_vanilla_check_scalar(value, name, positive)
    if value != math.floor(value):
        raise ValueError(f"{name} must be an integer scalar")


def _algorithm01_vanilla_validate_model(model, bridge):
    """Check that the model supplies the functions needed for this draw."""
    if not isinstance(model, dict):
        raise ValueError("model must be a dictionary")
    if not callable(model.get("phi")):
        raise ValueError("model['phi'] must be a function")
    if not callable(model.get("phi_bound")):
        raise ValueError("model['phi_bound'] must be a function")
    if not bridge and not callable(model.get("sample_endpoint")):
        raise ValueError("model['sample_endpoint'] is required for a random endpoint")


def _algorithm01_vanilla_named_value(draw, name):
    """Extract one numerical field from a draw or a one-row list."""
    if isinstance(draw, (list, tuple)):
        if len(draw) != 1:
            raise ValueError("Expected one extremum draw")
        draw = draw[0]
    if not isinstance(draw, dict) or name not in draw:
        raise ValueError(f"Extremum draw must contain {name}")

    value = draw[name]
    if isinstance(value, (list, tuple)):
        if len(value) != 1:
            raise ValueError(f"{name} must contain one value")
        value = value[0]
    _algorithm01_vanilla_check_scalar(value, name)
    return float(value)


def _algorithm01_vanilla_rbmmax(r, T):
    """Draw one restricted-meander maximum and its location."""
    draw = RBMMax_Vanilla(r=r, T=T)
    return {
        "M": _algorithm01_vanilla_named_value(draw, "M"),
        "tau": _algorithm01_vanilla_named_value(draw, "tau"),
    }


def _algorithm01_vanilla_make_poisson(T, M_phi):
    """Generate a unit-rate Poisson process on [0, T] x [0, M_phi].

    Times arrive with exponential waiting times of rate M_phi. Each time
    receives an independent uniform height in [0, M_phi]. Consequently,
    the number of points is Poisson with mean T*M_phi. The times are
    already sorted; no separate Poisson-count sampler is needed.
    """
    _algorithm01_vanilla_check_scalar(T, "T", positive=True)
    _algorithm01_vanilla_check_scalar(M_phi, "M_phi")
    if M_phi < 0:
        raise ValueError("M_phi must be nonnegative")
    if M_phi == 0:
        return []

    points = []
    current_time = 0.0

    while True:
        waiting_time = random.expovariate(M_phi)
        # A computer uniform draw can be exactly zero; an exponential gap cannot.
        if waiting_time == 0.0:
            continue

        next_time = current_time + waiting_time
        if next_time >= T:
            break
        if next_time <= current_time:
            raise ArithmeticError("Poisson time increment is below floating-point resolution")

        points.append({
            "index": len(points) + 1,
            "time": next_time,
            "height": random.random() * M_phi,
            "piece": None,
            "value": None,
            "phi": None,
        })
        current_time = next_time

    return points


def _algorithm01_vanilla_fill_piece(
    poisson, piece_id, start_time, end_time, start_value, end_value, lower, upper,
):
    """Fill the Poisson-time values within one constrained bridge piece."""
    out = []
    for point in poisson:
        out.append(point.copy())

    indices = []
    local_times = []
    for i in range(len(out)):
        if start_time < out[i]["time"] < end_time:
            indices.append(i)
            local_times.append(out[i]["time"] - start_time)

    if len(indices) == 0:
        return {"poisson": out, "icb_calls": 0}

    Delta = end_time - start_time
    if Delta <= 0:
        raise ValueError("Poisson point assigned to a zero-length piece")

    sampled = ICB(
        Delta=Delta, x=start_value, z=end_value, l=lower, u=upper,
        calT=local_times, include_endpoints=False,
    )
    for j in range(len(indices)):
        out[indices[j]]["piece"] = piece_id
        out[indices[j]]["value"] = sampled[j]["value"]

    return {"poisson": out, "icb_calls": 1}


def _algorithm01_vanilla_fill_poisson_values(poisson, pieces):
    """Fill all four pieces, keeping each time paired with its height."""
    out = poisson
    icb_calls = 0

    for piece in pieces:
        filled = _algorithm01_vanilla_fill_piece(
            poisson=out,
            piece_id=piece["piece"],
            start_time=piece["start_time"],
            end_time=piece["end_time"],
            start_value=piece["start_value"],
            end_value=piece["end_value"],
            lower=piece["lower"],
            upper=piece["upper"],
        )
        out = filled["poisson"]
        icb_calls = icb_calls + filled["icb_calls"]

    for point in out:
        if point["value"] is None or not math.isfinite(point["value"]):
            raise ValueError("Failed to assign every Poisson point to an ICB piece")

    return {"poisson": out, "icb_calls": icb_calls}


def _algorithm01_vanilla_build_pieces(x, Z, T, B_max, tau_plus, mL, tL, mR, tR):
    """Describe the four constrained bridges between successive extrema."""
    times = [0.0, tL, tau_plus, tR, T]
    values = [x, mL, B_max, mR, Z]
    lower_bounds = [mL, mL, mR, mR]
    pieces = []

    for i in range(4):
        pieces.append({
            "piece": i + 1,
            "start_time": times[i],
            "end_time": times[i + 1],
            "start_value": values[i],
            "end_value": values[i + 1],
            "lower": lower_bounds[i],
            "upper": B_max,
        })

    return pieces


def _algorithm01_vanilla_one(model, x, T, z, record_timing=False):
    """Repeat the full proposal, optionally timing all accepted/rejected work."""
    bridge = z is not None
    proposal_count = 0
    bridge_max_calls = 0
    rbmmax_calls = 0
    icb_calls = 0
    total_poisson_points = 0

    if record_timing:
        total_start = perf_counter()
        timing = {
            "endpoint_proposal": 0.0,
            "bridge_max": 0.0,
            "rbmmax": 0.0,
            "phi_bound_poisson": 0.0,
            "icb_phi_accept": 0.0,
        }

    while True:
        proposal_count = proposal_count + 1

        # Step 2: choose a new endpoint, or retain the prescribed bridge endpoint.
        if record_timing:
            bucket_start = perf_counter()
        if bridge:
            Z = z
        else:
            Z = model["sample_endpoint"](x=x, T=T)
            if isinstance(Z, (list, tuple)):
                if len(Z) != 1:
                    raise ValueError("sample_endpoint must return one endpoint")
                Z = Z[0]
        _algorithm01_vanilla_check_scalar(Z, "proposal endpoint Z")
        if record_timing:
            timing["endpoint_proposal"] += perf_counter() - bucket_start

        # Steps 3-5: reconstruct the maximum and the two sidewise minima.
        if record_timing:
            bucket_start = perf_counter()
        bridge_max = BRIDGEMAX(x=x, z=Z, T=T)
        bridge_max_calls = bridge_max_calls + 1
        B_max = _algorithm01_vanilla_named_value(bridge_max, "M")
        tau_plus = _algorithm01_vanilla_named_value(bridge_max, "tau")
        if not (B_max > max(x, Z) and 0.0 < tau_plus < T):
            raise ArithmeticError("Brownian-bridge extremum is degenerate at working precision")
        if record_timing:
            timing["bridge_max"] += perf_counter() - bucket_start

        if record_timing:
            bucket_start = perf_counter()
        left = _algorithm01_vanilla_rbmmax(r=B_max - x, T=tau_plus)
        right = _algorithm01_vanilla_rbmmax(r=B_max - Z, T=T - tau_plus)
        rbmmax_calls = rbmmax_calls + 2
        if record_timing:
            timing["rbmmax"] += perf_counter() - bucket_start

        if record_timing:
            bucket_start = perf_counter()
        HL = left["M"]
        sigmaL = left["tau"]
        HR = right["M"]
        sigmaR = right["tau"]

        mL = B_max - HL
        tL = tau_plus - sigmaL
        mR = B_max - HR
        tR = tau_plus + sigmaR
        B_min = min(mL, mR)
        if not (0.0 < tL < tau_plus < tR < T and mL < x and mR < Z):
            raise ArithmeticError("Restricted-meander extrema are degenerate at working precision")

        # Steps 6-7: bound phi on the range and generate all Poisson points.
        M_phi = model["phi_bound"](B_min, B_max)
        _algorithm01_vanilla_check_scalar(M_phi, "M_phi")
        if M_phi < 0:
            raise ValueError("model['phi_bound'] returned a negative value")

        poisson = _algorithm01_vanilla_make_poisson(T=T, M_phi=M_phi)
        total_poisson_points = total_poisson_points + len(poisson)
        pieces = _algorithm01_vanilla_build_pieces(
            x, Z, T, B_max, tau_plus, mL, tL, mR, tR,
        )
        if record_timing:
            timing["phi_bound_poisson"] += perf_counter() - bucket_start

        # Steps 8-10: reveal path values, then test every height against phi.
        if record_timing:
            bucket_start = perf_counter()
        accept = True
        if len(poisson) > 0:
            filled = _algorithm01_vanilla_fill_poisson_values(poisson, pieces)
            poisson = filled["poisson"]
            icb_calls = icb_calls + filled["icb_calls"]

            for point in poisson:
                phi_value = model["phi"](point["value"])
                _algorithm01_vanilla_check_scalar(phi_value, "model phi value")
                if phi_value < -1e-10:
                    raise ValueError("model['phi'] must return nonnegative values")
                if phi_value > M_phi + 1e-8 * max(1.0, M_phi):
                    raise ValueError("model['phi_bound'] is not a valid bound on this range")

                point["phi"] = phi_value
                if point["height"] <= phi_value:
                    accept = False
        if record_timing:
            timing["icb_phi_accept"] += perf_counter() - bucket_start

        # A rejection restarts at Step 2; all counters retain rejected work.
        if not accept:
            continue

        if record_timing:
            # Stop before assembling the returned skeleton, as in Table 2.
            total_elapsed = perf_counter() - total_start
            measured_elapsed = sum(timing.values())
            timing["other"] = total_elapsed - measured_elapsed
            timing["total"] = total_elapsed

        roles = ["start", "left_min", "maximum", "right_min", "end"]
        anchor_times = [0.0, tL, tau_plus, tR, T]
        anchor_values = [x, mL, B_max, mR, Z]
        extrema = []
        for i in range(5):
            extrema.append({
                "role": roles[i], "time": anchor_times[i], "value": anchor_values[i],
            })

        skeleton = []
        for point in poisson:
            skeleton.append({"time": point["time"], "value": point["value"]})

        draw = {
            "accepted": True,
            "bridge": bridge,
            "model_name": model.get("name"),
            "x": x,
            "T": T,
            "z": z,
            "endpoint": Z,
            "range": {"lower": B_min, "upper": B_max},
            "M_phi": M_phi,
            "maximum": {"value": B_max, "time": tau_plus},
            "left": {"H": HL, "sigma": sigmaL, "minimum": mL, "time": tL},
            "right": {"H": HR, "sigma": sigmaR, "minimum": mR, "time": tR},
            "pieces": pieces,
            "poisson": poisson,
            "skeleton": skeleton,
            "lambda": extrema,
            "stats": {
                "proposals": proposal_count,
                "bridge_max_calls": bridge_max_calls,
                "rbmmax_calls": rbmmax_calls,
                "icb_calls": icb_calls,
                "total_poisson_points": total_poisson_points,
                "accepted_poisson_points": len(poisson),
            },
        }
        if record_timing:
            draw["timing"] = timing
        return draw


def Algorithm01_Vanilla(model, x, T, z=None, n=1, record_timing=False):
    """Draw n diffusion skeletons, optionally with a fixed final endpoint z.

    model supplies phi(value), phi_bound(lower, upper), and, when z is
    omitted, sample_endpoint(x, T). The endpoint sampler may return one
    number or a one-element list. The model must satisfy the paper's
    assumptions; checking its functions at sampled points cannot prove a
    global bound or verify the endpoint proposal law.

    For n=1 return one dictionary. Otherwise return a list of dictionaries.
    Each draw retains the Poisson skeleton, extrema (under key 'lambda'),
    four bridge pieces, and counters including work on rejected proposals.
    There is no artificial outer rejection limit.

    Set record_timing=True to add a 'timing' dictionary of wall-clock
    seconds for the endpoint proposal, BRIDGEMAX, RBMMax, phi-bound/Poisson,
    ICB/phi/acceptance, residual operations, and total. These sampler-core
    timings accumulate rejected and accepted proposals. They exclude
    initial argument validation, constructing the returned skeleton, and
    any work done by the caller. No clock is read when record_timing=False.
    """
    _algorithm01_vanilla_check_scalar(x, "x")
    _algorithm01_vanilla_check_scalar(T, "T", positive=True)
    _algorithm01_vanilla_check_integer(n, "n", positive=True)
    if not isinstance(record_timing, bool):
        raise ValueError("record_timing must be True or False")
    if z is not None:
        _algorithm01_vanilla_check_scalar(z, "z")
    _algorithm01_vanilla_validate_model(model, bridge=z is not None)

    n = int(n)
    if n == 1:
        return _algorithm01_vanilla_one(model, x, T, z, record_timing)

    draws = []
    for _ in range(n):
        draws.append(_algorithm01_vanilla_one(model, x, T, z, record_timing))
    return draws


def _algorithm01_vanilla_known_value(draw, time, tolerance):
    """Look up an already revealed extremum, endpoint, or Poisson value."""
    for point in draw["lambda"]:
        if abs(point["time"] - time) <= tolerance:
            return {"found": True, "value": point["value"], "source": point["role"]}

    for point in draw["poisson"]:
        if abs(point["time"] - time) <= tolerance:
            return {"found": True, "value": point["value"], "source": "poisson"}

    return {"found": False, "value": None, "source": None}


def _algorithm01_vanilla_refine_piece(
    draw, piece, times, indices, values, sources, tolerance,
):
    """Refine one piece, splitting it at every accepted Poisson-time anchor."""
    values = values.copy()
    sources = sources.copy()
    if len(indices) == 0:
        return {"values": values, "sources": sources}

    anchors = [
        {"time": piece["start_time"], "value": piece["start_value"]},
        {"time": piece["end_time"], "value": piece["end_value"]},
    ]
    for point in draw["poisson"]:
        if point["piece"] == piece["piece"]:
            if piece["start_time"] < point["time"] < piece["end_time"]:
                anchors.append({"time": point["time"], "value": point["value"]})
    anchors.sort(key=lambda point: point["time"])

    for j in range(len(anchors) - 1):
        left_time = anchors[j]["time"]
        right_time = anchors[j + 1]["time"]
        interval_indices = []
        for i in indices:
            if left_time + tolerance < times[i] < right_time - tolerance:
                interval_indices.append(i)
        if len(interval_indices) == 0:
            continue

        # Sample each distinct requested time once, including repeated requests.
        requested_times = []
        for i in interval_indices:
            if times[i] not in requested_times:
                requested_times.append(times[i])
        requested_times.sort()
        local_times = []
        for time in requested_times:
            local_times.append(time - left_time)

        sampled = ICB(
            Delta=right_time - left_time,
            x=anchors[j]["value"], z=anchors[j + 1]["value"],
            l=piece["lower"], u=piece["upper"],
            calT=local_times, include_endpoints=False,
        )
        for i in interval_indices:
            position = requested_times.index(times[i])
            values[i] = sampled[position]["value"]
            sources[i] = f"piece_{piece['piece']}"

    return {"values": values, "sources": sources}


def Algorithm01_Vanilla_refine(draw, times, tolerance=1e-10):
    """Sample new values conditional on an accepted skeleton and its extrema.

    Return rows with time, value, and source in the requested order. Equal
    requested times receive the same value. Times within tolerance of known
    times reuse their known values; times just outside [0,T] are clamped.

    This does not modify draw or store the newly sampled values in it.
    Request all desired new times together for a joint conditional draw.
    Separate calls complete the original skeleton afresh; they do not
    condition on values produced by earlier calls.
    """
    if not isinstance(draw, dict) or draw.get("accepted") is not True:
        raise ValueError("draw must be an accepted Algorithm01_Vanilla draw")
    for name in ("T", "lambda", "poisson", "pieces"):
        if name not in draw:
            raise ValueError(f"draw must contain {name}")
    _algorithm01_vanilla_check_scalar(tolerance, "tolerance")
    if tolerance < 0:
        raise ValueError("tolerance must be nonnegative")
    if not isinstance(times, (list, tuple)):
        raise ValueError("times must be a list or tuple of finite numbers")

    requested_times = []
    for time in times:
        _algorithm01_vanilla_check_scalar(time, "requested time")
        if time < -tolerance or time > draw["T"] + tolerance:
            raise ValueError("times must lie inside [0, T]")
        requested_times.append(min(draw["T"], max(0.0, time)))

    values = [None] * len(requested_times)
    sources = [None] * len(requested_times)
    unresolved = []
    for i in range(len(requested_times)):
        known = _algorithm01_vanilla_known_value(draw, requested_times[i], tolerance)
        if known["found"]:
            values[i] = known["value"]
            sources[i] = known["source"]
        else:
            unresolved.append(i)

    for piece in draw["pieces"]:
        indices = []
        for i in unresolved:
            if piece["start_time"] + tolerance < requested_times[i] < piece["end_time"] - tolerance:
                indices.append(i)
        refined = _algorithm01_vanilla_refine_piece(
            draw, piece, requested_times, indices, values, sources, tolerance,
        )
        values = refined["values"]
        sources = refined["sources"]

    rows = []
    for i in range(len(requested_times)):
        if values[i] is None or not math.isfinite(values[i]):
            raise ValueError("Failed to refine one or more requested times")
        rows.append({"time": requested_times[i], "value": values[i], "source": sources[i]})
    return rows


def Algorithm01_Vanilla_summary(draws):
    """Return one row of sampling statistics for each accepted draw."""
    if isinstance(draws, dict):
        draws = [draws]
    if not isinstance(draws, (list, tuple)):
        raise ValueError("draws must be one accepted draw or a list of draws")

    rows = []
    for i in range(len(draws)):
        draw = draws[i]
        if not isinstance(draw, dict) or draw.get("accepted") is not True:
            raise ValueError("Every draw must be an accepted Algorithm01_Vanilla draw")
        rows.append({
            "draw": i + 1,
            "endpoint": draw["endpoint"],
            "proposals": draw["stats"]["proposals"],
            "K": draw["stats"]["accepted_poisson_points"],
            "M_phi": draw["M_phi"],
            "range_lower": draw["range"]["lower"],
            "range_upper": draw["range"]["upper"],
            "rbmmax_calls": draw["stats"]["rbmmax_calls"],
            "icb_calls": draw["stats"]["icb_calls"],
            "total_poisson_points": draw["stats"]["total_poisson_points"],
        })
    return rows
